rewrite themer
Aliucord/AliucordRN pull request #53
Opened 2023-01-08 04:53 UTC by amsyarasyiq

Conflicting with #52, and it fixes of it included as well

2023-01-08 17:38 UTC, rushiiMachine requested changes
Also move patchTheme & theme-init.ts to src/themer/patchTheme.ts & src/themer/themerInit.ts respectively

2023-01-08 17:38 UTC, rushiiMachine commented on src/theme-init.ts
> +export let ThemeState = {} as {
camelCase

2023-01-08 17:38 UTC, rushiiMachine commented on src/theme-init.ts
> +export function loadTheme(constants: ThemeConstants) {
confusing name, just go back to `initThemer`

2023-01-08 17:38 UTC, rushiiMachine commented on src/theme-init.ts
> +    HAS_THEME_NO_SETTINGS = "Themes exists but no settings",
simplify to `NO_SETTINGS`

2023-01-08 23:23 UTC, amsyarasyiq commented
Applied suggestions

2023-01-09 18:44 UTC, nikosszzz approved these changes

2023-01-10 16:55 UTC, rushiiMachine requested changes

2023-01-10 16:55 UTC, rushiiMachine commented on src/themer/patchTheme.ts
> +                    } else if (UnsyncedUserSettingsStore.useAMOLEDTheme === 2) {
can't you use the AMOLED state enum

2023-01-10 17:24 UTC, amsyarasyiq commented on src/themer/patchTheme.ts
> +                    } else if (UnsyncedUserSettingsStore.useAMOLEDTheme === 2) {
Replaced with enum

2023-01-10 17:30 UTC, rushiiMachine approved these changes

2023-01-10 17:30 UTC, merged