feat: plugin settings pages & UI upgrades
Aliucord/AliucordRN pull request #57
Opened 2023-01-16 17:26 UTC by nikosszzz

2023-01-19 05:38 UTC, rushiiMachine requested changes

2023-01-19 05:38 UTC, rushiiMachine commented on src/api/PluginManager.ts
> +                isDismissable: false,
why?

2023-01-19 05:38 UTC, rushiiMachine commented on src/api/PluginManager.ts
> +        if (!pluginInstance.localPath) {
just move this inside the try below you don't need to duplicate the dialog

2023-01-19 05:38 UTC, rushiiMachine commented on src/api/PluginManager.ts
> +                repo: "",
link to rn repo instead

2023-01-19 05:38 UTC, rushiiMachine commented on src/api/PluginManager.ts
> +    logger.info(`Loading plugin from ${pluginZip}`);
.zip is intentional

2023-01-19 05:38 UTC, rushiiMachine commented on src/api/PluginManager.ts
> +        if (pluginName && plugins[pluginName]) plugins[pluginName].errors += err.stack;
```suggestion
        plugins[pluginName]?.errors += err?.stack ?? err;
```

2023-01-19 05:38 UTC, rushiiMachine commented on src/api/PluginManager.ts
> +        loadedPlugin.errors += err.stack;
```suggestion
        loadedPlugin.errors += err?.stack ?? err;
```

2023-01-19 05:38 UTC, rushiiMachine commented on src/entities/Plugin.ts
> +    public getSettingsPage?(props: any[]): React.ReactElement;
what is props in this instance

2023-01-19 05:38 UTC, rushiiMachine commented on src/ui/PluginsPage.tsx
> +                                        {a.name}{i !== (plugin.authors as Author[]).length - 1 && <Text style={styles.text}>, </Text>}
just extract this into a variable it's unreadable

2023-01-19 05:38 UTC, rushiiMachine commented on src/ui/ThemesPage.tsx
> +                                        {a.name}{i !== (theme.authors as Author[]).length - 1 && <Text style={styles.text}>, </Text>}
same here

2023-01-19 05:38 UTC, rushiiMachine commented on src/ui/patchSettings.tsx
>  import { sha } from "aliucord-version";
can we move this file under somewhere else
like under src/patches 
\+ the themer/patcheTheme.tsx and then themerInit can go in root by itself

2023-01-21 08:24 UTC, amsyarasyiq commented
major changes that have to be reviewed again:

- ui directory has been reorganized
	- `ui/components` and `ui/pages` has been created
	- some files have been moved into their respective folder
- stylesheets used across pages are now merged (export of `ui/components`)
- most of `PluginCard` and `ThemeCard` has been moved to `ui/components/Card`

2023-01-21 17:33 UTC, rushiiMachine approved these changes

2023-01-21 17:41 UTC, merged